site_name: JSolr

pages:
    - Home: index.md
    - Server Requirements: server_requirements.md
    - Installation: installation.md
    - Getting Started: getting_started.md
    - Configuration: configuration.md
    - Indexing: indexing.md
    - Searching: searching.md
    - Advanced Search: advanced-search.md
    - Field Aliasing: field-aliasing.md
    - Dimensions: dimensions.md
    - XML Form Definitions: xml-form-definitions.md
    - Form Fields: form-fields.md
    - Calendar: calendartool.md
    - Facet: facets.md
    - FilterList: filterlist.md
    - Sort: sort.md
    - Browsing: browsing.md
    - Extending JSolr: extending_jsolr.md
    - Plugin Events: plugin_events.md
    - Developing a Plugin: developing_a_plugin.md
    - Language Management: language-management.md
